#ETHERNET
set_property PACKAGE_PIN L20 [get_ports GMII_RSTn]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RSTn]
set_property PACKAGE_PIN M28 [get_ports GMII_TX_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_CLK]
set_property PACKAGE_PIN K30 [get_ports GMII_GTXCLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_GTXCLK]
set_property PACKAGE_PIN M27 [get_ports GMII_TX_EN]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_EN]
set_property PACKAGE_PIN N29 [get_ports GMII_TX_ER]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_TX_ER]
set_property PACKAGE_PIN N27 [get_ports {GMII_TXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[0]}]
set_property PACKAGE_PIN N25 [get_ports {GMII_TXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[1]}]
set_property PACKAGE_PIN M29 [get_ports {GMII_TXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[2]}]
set_property PACKAGE_PIN L28 [get_ports {GMII_TXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[3]}]
set_property PACKAGE_PIN J26 [get_ports {GMII_TXD[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[4]}]
set_property PACKAGE_PIN K26 [get_ports {GMII_TXD[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[5]}]
set_property PACKAGE_PIN L30 [get_ports {GMII_TXD[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[6]}]
set_property PACKAGE_PIN J28 [get_ports {GMII_TXD[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_TXD[7]}]
set_property PACKAGE_PIN U27 [get_ports GMII_RX_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_CLK]
set_property PACKAGE_PIN R28 [get_ports GMII_RX_DV]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_DV]
set_property PACKAGE_PIN V26 [get_ports GMII_RX_ER]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_RX_ER]
set_property PACKAGE_PIN U30 [get_ports {GMII_RXD[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[0]}]
set_property PACKAGE_PIN U25 [get_ports {GMII_RXD[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[1]}]
set_property PACKAGE_PIN T25 [get_ports {GMII_RXD[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[2]}]
set_property PACKAGE_PIN U28 [get_ports {GMII_RXD[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[3]}]
set_property PACKAGE_PIN R19 [get_ports {GMII_RXD[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[4]}]
set_property PACKAGE_PIN T27 [get_ports {GMII_RXD[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[5]}]
set_property PACKAGE_PIN T26 [get_ports {GMII_RXD[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[6]}]
set_property PACKAGE_PIN T28 [get_ports {GMII_RXD[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GMII_RXD[7]}]
set_property PACKAGE_PIN R30 [get_ports GMII_CRS]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_CRS]
set_property PACKAGE_PIN W19 [get_ports GMII_COL]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_COL]
set_property PACKAGE_PIN R23 [get_ports GMII_MDC]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_MDC]
set_property PACKAGE_PIN J21 [get_ports GMII_MDIO]
set_property IOSTANDARD LVCMOS25 [get_ports GMII_MDIO]


set_property PACKAGE_PIN Y29 [get_ports GPIO_SWITCH_0]
set_property IOSTANDARD LVCMOS25 [get_ports GPIO_SWITCH_0]

set_property PACKAGE_PIN L21 [get_ports I2C_SDA]
set_property PACKAGE_PIN K21 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SCL]

#LED
set_property PACKAGE_PIN G19 [get_ports LED_GMII_OK]
set_property IOSTANDARD LVCMOS25 [get_ports LED_GMII_OK]
set_property PACKAGE_PIN E18 [get_ports LED_TCP_open]
set_property IOSTANDARD LVCMOS25 [get_ports LED_TCP_open]


create_clock -period 40.000 -waveform {0.000 20.000} [get_ports GMII_TX_CLK]
create_clock -period 8.000 -waveform {0.000 4.000} [get_ports GMII_RX_CLK]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_gen/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {tx_data[0]} {tx_data[1]} {tx_data[2]} {tx_data[3]} {tx_data[4]} {tx_data[5]} {tx_data[6]} {tx_data[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_gen/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {tx_fifo_data[0]} {tx_fifo_data[1]} {tx_fifo_data[2]} {tx_fifo_data[3]} {tx_fifo_data[4]} {tx_fifo_data[5]} {tx_fifo_data[6]} {tx_fifo_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list FIFO_RD_EN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list FIFO_VALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list FIFO_WR_EN]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list sda_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list tx_fifo_data_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLK_40M]
